name: absensi_mobile_apps
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  mobile_scanner: ^2.1.0
  qr_flutter: ^4.1.0
  http: ^0.13.3
  path_provider: ^2.1.2
  art_sweetalert: ^0.0.5
  intl: ^0.17.0
  gsheets: ^0.4.2
  googleapis: ^8.0.0
  googleapis_auth: ^1.3.1
  get: ^4.6.4
  permission_handler: ^11.0.0
  share_plus: ^7.2.2
  flutter_barcode_scanner: ^2.0.0
  geolocator: 9.0.2
  geocoding: 3.0.0
  google_maps_flutter: ^2.6.1
  # connectivity_plus: ^6.0.3
  # data_table_2: ^2.5.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/splash.png
